name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC 10 & G++ 10
        run: sudo apt update && sudo apt install gcc-10 g++-10

      - name: Initialize Submodules
        run: git submodule init && git submodule update

      - name: Configure CMake
        run: >
          cmake -B ${{github.workspace}}/build
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/external/vcpkg/scripts/buildsystems/vcpkg.cmake
        env:
          CC:   gcc-10
          CXX:  g++-10

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build/tests
        run: ctest -C ${{env.BUILD_TYPE}}
